# Generated by Django 4.2 on 2023-05-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Maincateory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subcateory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('basesize', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalprice', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('pic1', models.ImageField(upload_to='product')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
                ('Maincateory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.maincateory')),
                ('Subcateory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcateory')),
            ],
        ),
    ]
