# Generated by Django 4.2 on 2023-05-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_contact_checkoutproducts_qty_checkoutproducts_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=-123334),
        ),
    ]
